apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUFTNUlTSUkwVjZjSlZRSWdzNTh1X2loT21VUDRyRGl2ZVEwdERlR0w0UEtNSHBsQnk2bE8wWnZmTXVZSkNrUmVDQUpDQUtCS1h4SHBGVXhu
