apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUFTNUlTSUkwRWRmNnFXRGdabGJ1X0lITDFFYkFCWW5WNW8zWkdkT0JDQ0lYZjZPM0tZeHI0T3NZSGw4T0pYY2FORllBNDZPUUMxdTduZ0hs
