apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  webhook:
      ssm_opsitems_notifications:
        port: "14000"
        endpoint: /opsitems
        method: POST
      ssm_parameterstore_notifications:
        port: "12000"
        endpoint: /ssm-parameters-notifications
        method: POST
