apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-ssm-paramnotf
  namespace: argo-events
spec:
  service:
    ports:
      - name: ssm_parameterstore_notifications
        port: 12000
        targetPort: 12000
  webhook:
      ssm_parameterstore_notifications:
        port: "12000"
        endpoint: /ssm-parameters-notifications
        method: POST
