apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-ssm-opsitemsnotf
  namespace: argo-events
spec:
  service:
    ports:
      - name: ssm-opsitems-notifications
        port: 14000
        targetPort: 14000
  webhook:
      ssm-opsitems-notifications:
        port: "14000"
        endpoint: /opsitems
        method: POST
