apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argoworkflow-sns-eventsource-lbtargets
  namespace: argo-events
spec:
  serviceRef:
    name: webhook-ssm-paramnotf-eventsource-svc
    port: 12000
  targetGroupARN: {{.Values.events.sns_tg_arn}}
